### ISSUE TITLE
AzureHttpRouter constructor throws an exception

### ISSUE THREAD

**Issue by skapoor8** [nestjs/azure-func-http#1019]
Hi Nest.js team! I'm running into the following issue while using this package. Thanks in advance for your help! I'm really loving nest.js so far and really looking forward to getting my project working on an azure function app!

## I'm submitting a...
[ ] Regression
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 

## Current behavior
AzureHttpRouter constructor is throwing an exception:

```
[2022-11-15T15:44:11.885Z] Executing HTTP request: {
[2022-11-15T15:44:11.885Z]   requestId: "da9a6aa2-4bcc-42a2-8f2d-f3969f01ecf4",
[2022-11-15T15:44:11.885Z]   method: "GET",
[2022-11-15T15:44:11.886Z]   userAgent: "PostmanRuntime/7.28.4",
[2022-11-15T15:44:11.886Z]   uri: "/"
[2022-11-15T15:44:11.886Z] }
[2022-11-15T15:44:11.973Z] Executing 'Functions.main' (Reason='This function was programmatically called via the host APIs.', Id=12eac574-6fe4-49dd-baee-619866eb4be0)
[2022-11-15T15:44:12.006Z] Received FunctionInvocationRequest
[2022-11-15T15:44:12.006Z] (node:1922) UnhandledPromiseRejectionWarning: TypeError: trouter_1.default is not a constructor
[2022-11-15T15:44:12.006Z]     at new AzureHttpRouter (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/router/azure-http.router.js:12:15)
[2022-11-15T15:44:12.006Z]     at createApp (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/dist/src/main.azure.js:8:73)
[2022-11-15T15:44:12.006Z]     at AzureHttpAdapterStatic.<anonymous> (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/azure-http.adapter.js:24:31)
[2022-11-15T15:44:12.006Z]     at Generator.next (<anonymous>)
[2022-11-15T15:44:12.006Z]     at /Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/azure-http.adapter.js:8:71
[2022-11-15T15:44:12.006Z]     at new Promise (<anonymous>)
[2022-11-15T15:44:12.006Z]     at __awaiter (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/azure-http.adapter.js:4:12)
[2022-11-15T15:44:12.006Z]     at AzureHttpAdapterStatic.createHandler (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/azure-http.adapter.js:23:16)
[2022-11-15T15:44:12.006Z]     at AzureHttpAdapterStatic.handle (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/node_modules/@nestjs/azure-func-http/dist/azure-http.adapter.js:20:14)
[2022-11-15T15:44:12.006Z]     at Object.run (/Users/siddharthkapoor/Desktop/projects/OdapCloud/odap/dist/main/index.js:7:40)
```

I added dded @nestjs/azure-func-http to my project via nest cli. Added the AzureHttpRouter constructor into main.azure.ts as per documentation:

```ts
export async function createApp(): Promise<INestApplication> {
  const app = await NestFactory.create(AppModule, new AzureHttpRouter());
  // app.setGlobalPrefix('api');

  await app.init();
  return app;
}
```

Everything works fine if I don't use the AzureHttpRouter (i.e. using express instead), but I would like to be able to use it for faster routing.

I dug into the package, and observed the following code in dist/router/azure-http.router.ts

```ts
// at line 8
const trouter_1 = require("trouter");
const adapter_1 = require("../adapter");
class AzureHttpRouter extends core_1.AbstractHttpAdapter {
    constructor() {
        super(new trouter_1.default()); // <-- this is where the exception occurs
        this.routerMethodFactory = new router_method_factory_1.RouterMethodFactory();
    }
```

Everything works as expected if I change the above code as follows:

```ts
const trouter_1 = require("trouter");
const adapter_1 = require("../adapter");
class AzureHttpRouter extends core_1.AbstractHttpAdapter {
    constructor() {
        super(new trouter_1()); // <-- just removed default
        this.routerMethodFactory = new router_method_factory_1.RouterMethodFactory();
    }
```

## Expected behavior
`new AzureHttpRouter()` should not throw exception.

## Minimal reproduction of the problem with instructions
1.  With a matching environment as below, install nestjs/cli@8 (since 9 does not work with azure functions yet)
2. create a new nest project
3. add nestjs/azure-func-http
4. Build with `npm run build`
5. Serve with `func host start --verbose`

I experienced some issues at this point. Dist folder showed a single compiled main.js file, and the func logging complained that the scriptFile was not found. So I had to set the webpack config in nest-cli.json off (to get the dist/main/index.js file specified in the auto-generated main/function.json file) to get things working.

6. Add the AzureHttpRouter constructor in main.azure.ts as show above

## Environment
- nest version: 8.2.8
- nest/azure-func-http version: 0.8.0 
- node version: 14.18.2
- npm version: 6.14.15
- azure core func tools version: 4.0.4865
- platform: macbook pro m1

**Comment by bm77525-kr** [comment]
They refuse to acknowledge this as a bug: https://github.com/nestjs/azure-func-http/issues/636. Sounds like you'll have to reach out on discord

**Comment by levymoreira** [comment]
Same issue here.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
