### ISSUE TITLE
AzureHttpRouter not exported/not working

### ISSUE THREAD

**Issue by thetre97** [nestjs/azure-func-http#46]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When creating an app with the `AzureHttpRouter`, routing does not work.

## Expected behavior
In the README, it shows you can instantiate the app using an azure http router instead of the default express router. However, when adding this: `const app = await NestFactory.create(AppModule, new AzureHttpRouter());` the request to any endpoint just hangs.
Perhaps I need to do something else to get this to work?

Also, when I use this with Typescript, and run `build`, it says that `AzureHttpRouter` is not being exported from the `@nestjs/azure-func-http` package.

## Minimal reproduction of the problem with instructions
`yarn add @nestjs/azure-func-http`
`main.azure.[j/t]s`
```javascript
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { AzureHttpRouter } from '@nestjs/azure-func-http'

export async function createApp() {
  const app = await NestFactory.create(AppModule, new AzureHttpRouter());
  app.setGlobalPrefix('webhooks');

  await app.init();
  return app;
}
```

## Environment

<pre><code>
Nest version: 6.8.3
 
For Tooling issues:
- Node version: 10.16.2
- Platform:  Linux

Others:

</code></pre>

**Comment by vadistic** [comment]
Yeah, it's not there.

```

$ tree /home/vadistic/dev/rewarp/node_modules/@nestjs/azure-func-http/dist
/home/vadistic/dev/rewarp/node_modules/@nestjs/azure-func-http/dist
├── azure-http.adapter.d.ts
├── azure-http.adapter.js
├── index.d.ts
└── index.js

```

**Comment by thetre97** [comment]
I found I could build this locally. When I do, it creates a subfolder `router` inside dist, but it appears this is not uploaded to npm.
![image](https://user-images.githubusercontent.com/12587127/67700305-a2eef480-f9a5-11e9-8781-751e14b9dc80.png)

However, after linking this package to a project, and import via `import { AzureHttpRouter } from '@nestjs/azure-func-http/dist/router'` I get an error thrown:

```bash
No overload matches this call.
  Overload 1 of 2, '(module: any, options?: NestApplicationOptions): Promise<INestApplication>', gave the following error.
    Type 'AzureHttpRouter' has no properties in common with type 'NestApplicationOptions'.
  Overload 2 of 2, '(module: any, httpAdapter: AbstractHttpAdapter<any, any, any>, options?: NestApplicationOptions): Promise<INestApplication>', gave the following error.
    Argument of type 'AzureHttpRouter' is not assignable to parameter of type 'AbstractHttpAdapter<any, any, any>'.
      Property 'instance' is protected but type 'AbstractHttpAdapter<TServer, TRequest, TResponse>' is not a class derived from 'AbstractHttpAdapter<TServer, TRequest, TResponse>'.ts(2769)
```

**Comment by jparneodo** [comment]
With 0.3.1 :
Using <code>const app = await NestFactory.create(AppModule, new AzureHttpRouter());</code>

Log:
<pre>
[25/11/2019 00:41:30] [Nest] 36920   - 2019-11-25 1:41:30 AM   [NestFactory] Starting Nest application...                                                           
[25/11/2019 00:41:30] [Nest] 36920   - 2019-11-25 1:41:30 AM   [InstanceLoader] AppModule dependencies initialized +34ms                                            
[25/11/2019 00:41:30] [Nest] 36920   - 2019-11-25 1:41:30 AM   [InstanceLoader] UsersModule dependencies initialized +2ms                                           
[25/11/2019 00:41:30] [Nest] 36920   - 2019-11-25 1:41:30 AM   [InstanceLoader] GraphQLModule dependencies initialized +3ms                                         
[25/11/2019 00:41:30] (node:36920) UnhandledPromiseRejectionWarning: Error: No support for current HttpAdapter: AzureHttpRouter                                     
[25/11/2019 00:41:30]     at GraphQLModule.registerGqlServer (c:\DEV\node_modules\@nestjs\graphql\dist\graphql.module.js:132:19)    
[25/11/2019 00:41:30]     at GraphQLModule.<anonymous> (c:\DEV\node_modules\@nestjs\graphql\dist\graphql.module.js:116:18)          
[25/11/2019 00:41:30]     at Generator.next (<anonymous>)                                                                                                           
[25/11/2019 00:41:30]     at fulfilled (c:\DEV\node_modules\@nestjs\graphql\dist\graphql.module.js:17:58)  
</pre>

Something wrong here or with graphql configuration?

**Comment by Yhozen** [comment]
the graphql module only supports express and fastify as  seen [here](https://github.com/nestjs/graphql/blob/master/lib/graphql.module.ts) 
```typescript
/* GraphQLModule.registerGqlServer */
 if (platformName === 'express') {
      this.registerExpress(apolloOptions);
    } else if (platformName === 'fastify') {
      this.registerFastify(apolloOptions);
    } else {
      throw new Error(`No support for current HttpAdapter: ${platformName}`);
    }
  }
```

I think the only solution is to use express instead of AzureHttpRouter

**Comment by skapoor8** [comment]
Experiencing the same issue. `bash func host start` does not seem to work while using AzureHttpRouter :/
